-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Annotation
    = Annotation


type AnnotationConnection
    = AnnotationConnection


type AnnotationEdge
    = AnnotationEdge


type ArrowGeometry
    = ArrowGeometry


type CircleGeometry
    = CircleGeometry


type CloudFile
    = CloudFile


type Comment
    = Comment


type Document
    = Document


type Firm
    = Firm


type Form
    = Form


type FormField
    = FormField


type Group
    = Group


type Inspection
    = Inspection


type InspectionAvailabilityDate
    = InspectionAvailabilityDate


type InspectionConnection
    = InspectionConnection


type InspectionEdge
    = InspectionEdge


type InspectionItem
    = InspectionItem


type InspectionTemplate
    = InspectionTemplate


type InspectionTemplateItem
    = InspectionTemplateItem


type Issue
    = Issue


type Jurisdiction
    = Jurisdiction


type JurisdictionConnection
    = JurisdictionConnection


type JurisdictionEdge
    = JurisdictionEdge


type LineGeometry
    = LineGeometry


type Meeting
    = Meeting


type MeetingSchedule
    = MeetingSchedule


type Page
    = Page


type PageInfo
    = PageInfo


type Parcel
    = Parcel


type Permission
    = Permission


type Project
    = Project


type ProjectConnection
    = ProjectConnection


type ProjectEdge
    = ProjectEdge


type ProjectStep
    = ProjectStep


type ProjectStepTemplate
    = ProjectStepTemplate


type ProjectType
    = ProjectType


type PunchListItem
    = PunchListItem


type RectangleGeometry
    = RectangleGeometry


type ReviewRequest
    = ReviewRequest


type ShapeArrow
    = ShapeArrow


type ShapeCircle
    = ShapeCircle


type ShapeFreehand
    = ShapeFreehand


type ShapeLine
    = ShapeLine


type ShapePoint
    = ShapePoint


type ShapePolygon
    = ShapePolygon


type ShapeRectangle
    = ShapeRectangle


type Stamp
    = Stamp


type StampedDocument
    = StampedDocument


type Submission
    = Submission


type Task
    = Task


type User
    = User


type Version
    = Version
