-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Union exposing (..)


type DocumentableUnion
    = DocumentableUnion


type ReviewRequestableUnion
    = ReviewRequestableUnion


type ShapeUnion
    = ShapeUnion


type StepableUnion
    = StepableUnion


type TaskResourceUnion
    = TaskResourceUnion
