-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.CircleGeometry exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


center :
    SelectionSet decodesTo Api.Object.ShapePoint
    -> SelectionSet (Maybe decodesTo) Api.Object.CircleGeometry
center object_ =
    Object.selectionForCompositeField "center" [] object_ (identity >> Decode.nullable)


radius : SelectionSet (Maybe Float) Api.Object.CircleGeometry
radius =
    Object.selectionForField "(Maybe Float)" "radius" [] (Decode.float |> Decode.nullable)
