-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.CloudFile exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.CloudFile
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


contentType : SelectionSet (Maybe String) Api.Object.CloudFile
contentType =
    Object.selectionForField "(Maybe String)" "contentType" [] (Decode.string |> Decode.nullable)


filename : SelectionSet (Maybe String) Api.Object.CloudFile
filename =
    Object.selectionForField "(Maybe String)" "filename" [] (Decode.string |> Decode.nullable)


height : SelectionSet (Maybe Int) Api.Object.CloudFile
height =
    Object.selectionForField "(Maybe Int)" "height" [] (Decode.int |> Decode.nullable)


width : SelectionSet (Maybe Int) Api.Object.CloudFile
width =
    Object.selectionForField "(Maybe Int)" "width" [] (Decode.int |> Decode.nullable)


token : SelectionSet (Maybe String) Api.Object.CloudFile
token =
    Object.selectionForField "(Maybe String)" "token" [] (Decode.string |> Decode.nullable)


externalUrl : SelectionSet (Maybe String) Api.Object.CloudFile
externalUrl =
    Object.selectionForField "(Maybe String)" "externalUrl" [] (Decode.string |> Decode.nullable)


size : SelectionSet (Maybe String) Api.Object.CloudFile
size =
    Object.selectionForField "(Maybe String)" "size" [] (Decode.string |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.CloudFile
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.CloudFile
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


downloadUrl : SelectionSet (Maybe String) Api.Object.CloudFile
downloadUrl =
    Object.selectionForField "(Maybe String)" "downloadUrl" [] (Decode.string |> Decode.nullable)


uploadUrl : SelectionSet (Maybe String) Api.Object.CloudFile
uploadUrl =
    Object.selectionForField "(Maybe String)" "uploadUrl" [] (Decode.string |> Decode.nullable)


isUploaded : SelectionSet (Maybe String) Api.Object.CloudFile
isUploaded =
    Object.selectionForField "(Maybe String)" "isUploaded" [] (Decode.string |> Decode.nullable)
