-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Document exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.Document
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet (Maybe String) Api.Object.Document
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


isReady : SelectionSet (Maybe Bool) Api.Object.Document
isReady =
    Object.selectionForField "(Maybe Bool)" "isReady" [] (Decode.bool |> Decode.nullable)


commentCount : SelectionSet (Maybe Int) Api.Object.Document
commentCount =
    Object.selectionForField "(Maybe Int)" "commentCount" [] (Decode.int |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.Document
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.Document
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


submission :
    SelectionSet decodesTo Api.Object.Submission
    -> SelectionSet (Maybe decodesTo) Api.Object.Document
submission object_ =
    Object.selectionForCompositeField "submission" [] object_ (identity >> Decode.nullable)


versions :
    SelectionSet decodesTo Api.Object.Version
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Document
versions object_ =
    Object.selectionForCompositeField "versions" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


reviewRequests :
    SelectionSet decodesTo Api.Object.ReviewRequest
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Document
reviewRequests object_ =
    Object.selectionForCompositeField "reviewRequests" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


documentable :
    SelectionSet decodesTo Api.Union.DocumentableUnion
    -> SelectionSet (Maybe decodesTo) Api.Object.Document
documentable object_ =
    Object.selectionForCompositeField "documentable" [] object_ (identity >> Decode.nullable)
