-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.FormField exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


uuid : SelectionSet (Maybe String) Api.Object.FormField
uuid =
    Object.selectionForField "(Maybe String)" "uuid" [] (Decode.string |> Decode.nullable)


kind : SelectionSet (Maybe String) Api.Object.FormField
kind =
    Object.selectionForField "(Maybe String)" "kind" [] (Decode.string |> Decode.nullable)


value : SelectionSet (Maybe String) Api.Object.FormField
value =
    Object.selectionForField "(Maybe String)" "value" [] (Decode.string |> Decode.nullable)
