-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.InspectionItem exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.InspectionItem
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


title : SelectionSet (Maybe String) Api.Object.InspectionItem
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


isChecked : SelectionSet (Maybe Bool) Api.Object.InspectionItem
isChecked =
    Object.selectionForField "(Maybe Bool)" "isChecked" [] (Decode.bool |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.InspectionItem
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.InspectionItem
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


inspection :
    SelectionSet decodesTo Api.Object.Inspection
    -> SelectionSet (Maybe decodesTo) Api.Object.InspectionItem
inspection object_ =
    Object.selectionForCompositeField "inspection" [] object_ (identity >> Decode.nullable)
