-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.InspectionTemplate exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.InspectionTemplate
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet (Maybe String) Api.Object.InspectionTemplate
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


secondsPerSqFt : SelectionSet (Maybe Float) Api.Object.InspectionTemplate
secondsPerSqFt =
    Object.selectionForField "(Maybe Float)" "secondsPerSqFt" [] (Decode.float |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.InspectionTemplate
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.InspectionTemplate
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


jurisdiction :
    SelectionSet decodesTo Api.Object.Jurisdiction
    -> SelectionSet (Maybe decodesTo) Api.Object.InspectionTemplate
jurisdiction object_ =
    Object.selectionForCompositeField "jurisdiction" [] object_ (identity >> Decode.nullable)


users :
    SelectionSet decodesTo Api.Object.User
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.InspectionTemplate
users object_ =
    Object.selectionForCompositeField "users" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


items :
    SelectionSet decodesTo Api.Object.InspectionTemplateItem
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.InspectionTemplate
items object_ =
    Object.selectionForCompositeField "items" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
