-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.InspectionAvailabilityDate exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


day : SelectionSet (Maybe String) Api.Object.InspectionAvailabilityDate
day =
    Object.selectionForField "(Maybe String)" "day" [] (Decode.string |> Decode.nullable)


isAvailable : SelectionSet (Maybe Bool) Api.Object.InspectionAvailabilityDate
isAvailable =
    Object.selectionForField "(Maybe Bool)" "isAvailable" [] (Decode.bool |> Decode.nullable)


isScheduled : SelectionSet (Maybe Bool) Api.Object.InspectionAvailabilityDate
isScheduled =
    Object.selectionForField "(Maybe Bool)" "isScheduled" [] (Decode.bool |> Decode.nullable)
