-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Inspection exposing (..)

import Api.Enum.InspectionStatus
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.Inspection
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet (Maybe String) Api.Object.Inspection
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


status : SelectionSet (Maybe Api.Enum.InspectionStatus.InspectionStatus) Api.Object.Inspection
status =
    Object.selectionForField "(Maybe Enum.InspectionStatus.InspectionStatus)" "status" [] (Api.Enum.InspectionStatus.decoder |> Decode.nullable)


scheduledDate : SelectionSet (Maybe String) Api.Object.Inspection
scheduledDate =
    Object.selectionForField "(Maybe String)" "scheduledDate" [] (Decode.string |> Decode.nullable)


requestedTime : SelectionSet (Maybe String) Api.Object.Inspection
requestedTime =
    Object.selectionForField "(Maybe String)" "requestedTime" [] (Decode.string |> Decode.nullable)


suggestedTime : SelectionSet (Maybe String) Api.Object.Inspection
suggestedTime =
    Object.selectionForField "(Maybe String)" "suggestedTime" [] (Decode.string |> Decode.nullable)


notes : SelectionSet (Maybe String) Api.Object.Inspection
notes =
    Object.selectionForField "(Maybe String)" "notes" [] (Decode.string |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.Inspection
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.Inspection
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


availableDays :
    SelectionSet decodesTo Api.Object.InspectionAvailabilityDate
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Inspection
availableDays object_ =
    Object.selectionForCompositeField "availableDays" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


projectStep :
    SelectionSet decodesTo Api.Object.ProjectStep
    -> SelectionSet (Maybe decodesTo) Api.Object.Inspection
projectStep object_ =
    Object.selectionForCompositeField "projectStep" [] object_ (identity >> Decode.nullable)


assignedUser :
    SelectionSet decodesTo Api.Object.User
    -> SelectionSet (Maybe decodesTo) Api.Object.Inspection
assignedUser object_ =
    Object.selectionForCompositeField "assignedUser" [] object_ (identity >> Decode.nullable)


items :
    SelectionSet decodesTo Api.Object.InspectionItem
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Inspection
items object_ =
    Object.selectionForCompositeField "items" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


punchListItems :
    SelectionSet decodesTo Api.Object.PunchListItem
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Inspection
punchListItems object_ =
    Object.selectionForCompositeField "punchListItems" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
