-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.LineGeometry exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


p1 :
    SelectionSet decodesTo Api.Object.ShapePoint
    -> SelectionSet (Maybe decodesTo) Api.Object.LineGeometry
p1 object_ =
    Object.selectionForCompositeField "p1" [] object_ (identity >> Decode.nullable)


p2 :
    SelectionSet decodesTo Api.Object.ShapePoint
    -> SelectionSet (Maybe decodesTo) Api.Object.LineGeometry
p2 object_ =
    Object.selectionForCompositeField "p2" [] object_ (identity >> Decode.nullable)
