-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Page exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.Page
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


width : SelectionSet (Maybe Int) Api.Object.Page
width =
    Object.selectionForField "(Maybe Int)" "width" [] (Decode.int |> Decode.nullable)


integer : SelectionSet (Maybe Int) Api.Object.Page
integer =
    Object.selectionForField "(Maybe Int)" "integer" [] (Decode.int |> Decode.nullable)


calibration : SelectionSet (Maybe String) Api.Object.Page
calibration =
    Object.selectionForField "(Maybe String)" "calibration" [] (Decode.string |> Decode.nullable)


thumbnailUrl : SelectionSet (Maybe String) Api.Object.Page
thumbnailUrl =
    Object.selectionForField "(Maybe String)" "thumbnailUrl" [] (Decode.string |> Decode.nullable)


unresolvedCount : SelectionSet (Maybe Int) Api.Object.Page
unresolvedCount =
    Object.selectionForField "(Maybe Int)" "unresolvedCount" [] (Decode.int |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.Page
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.Page
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


version :
    SelectionSet decodesTo Api.Object.Version
    -> SelectionSet (Maybe decodesTo) Api.Object.Page
version object_ =
    Object.selectionForCompositeField "version" [] object_ (identity >> Decode.nullable)


annotations :
    SelectionSet decodesTo Api.Object.Annotation
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Page
annotations object_ =
    Object.selectionForCompositeField "annotations" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
