-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Parcel exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.Parcel
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


parcelId : SelectionSet (Maybe String) Api.Object.Parcel
parcelId =
    Object.selectionForField "(Maybe String)" "parcelId" [] (Decode.string |> Decode.nullable)


address : SelectionSet (Maybe String) Api.Object.Parcel
address =
    Object.selectionForField "(Maybe String)" "address" [] (Decode.string |> Decode.nullable)


lonlat : SelectionSet (Maybe String) Api.Object.Parcel
lonlat =
    Object.selectionForField "(Maybe String)" "lonlat" [] (Decode.string |> Decode.nullable)


owner : SelectionSet (Maybe String) Api.Object.Parcel
owner =
    Object.selectionForField "(Maybe String)" "owner" [] (Decode.string |> Decode.nullable)


acreage : SelectionSet (Maybe String) Api.Object.Parcel
acreage =
    Object.selectionForField "(Maybe String)" "acreage" [] (Decode.string |> Decode.nullable)


landUse : SelectionSet (Maybe String) Api.Object.Parcel
landUse =
    Object.selectionForField "(Maybe String)" "landUse" [] (Decode.string |> Decode.nullable)
