-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ProjectStepTemplate exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.ProjectStepTemplate
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet (Maybe String) Api.Object.ProjectStepTemplate
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Api.Object.ProjectStepTemplate
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


kind : SelectionSet (Maybe String) Api.Object.ProjectStepTemplate
kind =
    Object.selectionForField "(Maybe String)" "kind" [] (Decode.string |> Decode.nullable)


order : SelectionSet (Maybe Int) Api.Object.ProjectStepTemplate
order =
    Object.selectionForField "(Maybe Int)" "order" [] (Decode.int |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.ProjectStepTemplate
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.ProjectStepTemplate
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


jurisdiction :
    SelectionSet decodesTo Api.Object.Jurisdiction
    -> SelectionSet (Maybe decodesTo) Api.Object.ProjectStepTemplate
jurisdiction object_ =
    Object.selectionForCompositeField "jurisdiction" [] object_ (identity >> Decode.nullable)


projectType :
    SelectionSet decodesTo Api.Object.ProjectType
    -> SelectionSet (Maybe decodesTo) Api.Object.ProjectStepTemplate
projectType object_ =
    Object.selectionForCompositeField "projectType" [] object_ (identity >> Decode.nullable)
