-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Project exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.Project
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


internalId : SelectionSet (Maybe String) Api.Object.Project
internalId =
    Object.selectionForField "(Maybe String)" "internalId" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) Api.Object.Project
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


number : SelectionSet (Maybe String) Api.Object.Project
number =
    Object.selectionForField "(Maybe String)" "number" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Api.Object.Project
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


commentCount : SelectionSet (Maybe Int) Api.Object.Project
commentCount =
    Object.selectionForField "(Maybe Int)" "commentCount" [] (Decode.int |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.Project
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.Project
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


jurisdiction :
    SelectionSet decodesTo Api.Object.Jurisdiction
    -> SelectionSet (Maybe decodesTo) Api.Object.Project
jurisdiction object_ =
    Object.selectionForCompositeField "jurisdiction" [] object_ (identity >> Decode.nullable)


documents :
    SelectionSet decodesTo Api.Object.Document
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Project
documents object_ =
    Object.selectionForCompositeField "documents" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


permissions :
    SelectionSet decodesTo Api.Object.Permission
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Project
permissions object_ =
    Object.selectionForCompositeField "permissions" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


parcels :
    SelectionSet decodesTo Api.Object.Parcel
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Project
parcels object_ =
    Object.selectionForCompositeField "parcels" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


projectSteps :
    SelectionSet decodesTo Api.Object.ProjectStep
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Project
projectSteps object_ =
    Object.selectionForCompositeField "projectSteps" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
