-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ProjectStep exposing (..)

import Api.Enum.ProjectStepStatus
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.ProjectStep
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet (Maybe String) Api.Object.ProjectStep
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Api.Object.ProjectStep
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


kind : SelectionSet (Maybe String) Api.Object.ProjectStep
kind =
    Object.selectionForField "(Maybe String)" "kind" [] (Decode.string |> Decode.nullable)


status : SelectionSet (Maybe Api.Enum.ProjectStepStatus.ProjectStepStatus) Api.Object.ProjectStep
status =
    Object.selectionForField "(Maybe Enum.ProjectStepStatus.ProjectStepStatus)" "status" [] (Api.Enum.ProjectStepStatus.decoder |> Decode.nullable)


order : SelectionSet (Maybe Int) Api.Object.ProjectStep
order =
    Object.selectionForField "(Maybe Int)" "order" [] (Decode.int |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.ProjectStep
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.ProjectStep
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


stepable :
    SelectionSet decodesTo Api.Union.StepableUnion
    -> SelectionSet (Maybe decodesTo) Api.Object.ProjectStep
stepable object_ =
    Object.selectionForCompositeField "stepable" [] object_ (identity >> Decode.nullable)


project :
    SelectionSet decodesTo Api.Object.Project
    -> SelectionSet (Maybe decodesTo) Api.Object.ProjectStep
project object_ =
    Object.selectionForCompositeField "project" [] object_ (identity >> Decode.nullable)


projectStepTemplate :
    SelectionSet decodesTo Api.Object.ProjectStepTemplate
    -> SelectionSet (Maybe decodesTo) Api.Object.ProjectStep
projectStepTemplate object_ =
    Object.selectionForCompositeField "projectStepTemplate" [] object_ (identity >> Decode.nullable)
