-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PunchListItem exposing (..)

import Api.Enum.PunchListItemStatus
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.PunchListItem
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


note : SelectionSet (Maybe String) Api.Object.PunchListItem
note =
    Object.selectionForField "(Maybe String)" "note" [] (Decode.string |> Decode.nullable)


shapes :
    SelectionSet decodesTo Api.Union.ShapeUnion
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.PunchListItem
shapes object_ =
    Object.selectionForCompositeField "shapes" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


status : SelectionSet (Maybe Api.Enum.PunchListItemStatus.PunchListItemStatus) Api.Object.PunchListItem
status =
    Object.selectionForField "(Maybe Enum.PunchListItemStatus.PunchListItemStatus)" "status" [] (Api.Enum.PunchListItemStatus.decoder |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.PunchListItem
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.PunchListItem
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


submission :
    SelectionSet decodesTo Api.Object.Submission
    -> SelectionSet (Maybe decodesTo) Api.Object.PunchListItem
submission object_ =
    Object.selectionForCompositeField "submission" [] object_ (identity >> Decode.nullable)


imageCloudFile :
    SelectionSet decodesTo Api.Object.CloudFile
    -> SelectionSet (Maybe decodesTo) Api.Object.PunchListItem
imageCloudFile object_ =
    Object.selectionForCompositeField "imageCloudFile" [] object_ (identity >> Decode.nullable)
