-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ReviewRequest exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.ReviewRequest
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


status : SelectionSet (Maybe String) Api.Object.ReviewRequest
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.ReviewRequest
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.ReviewRequest
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


document :
    SelectionSet decodesTo Api.Object.Document
    -> SelectionSet (Maybe decodesTo) Api.Object.ReviewRequest
document object_ =
    Object.selectionForCompositeField "document" [] object_ (identity >> Decode.nullable)


reviewRequestable :
    SelectionSet decodesTo Api.Union.ReviewRequestableUnion
    -> SelectionSet (Maybe decodesTo) Api.Object.ReviewRequest
reviewRequestable object_ =
    Object.selectionForCompositeField "reviewRequestable" [] object_ (identity >> Decode.nullable)
