-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.StampedDocument exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.StampedDocument
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


isReady : SelectionSet (Maybe Bool) Api.Object.StampedDocument
isReady =
    Object.selectionForField "(Maybe Bool)" "isReady" [] (Decode.bool |> Decode.nullable)


downloadUrl : SelectionSet (Maybe String) Api.Object.StampedDocument
downloadUrl =
    Object.selectionForField "(Maybe String)" "downloadUrl" [] (Decode.string |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.StampedDocument
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.StampedDocument
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


version :
    SelectionSet decodesTo Api.Object.Version
    -> SelectionSet (Maybe decodesTo) Api.Object.StampedDocument
version object_ =
    Object.selectionForCompositeField "version" [] object_ (identity >> Decode.nullable)


stamp :
    SelectionSet decodesTo Api.Object.Stamp
    -> SelectionSet (Maybe decodesTo) Api.Object.StampedDocument
stamp object_ =
    Object.selectionForCompositeField "stamp" [] object_ (identity >> Decode.nullable)
