-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.User
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet (Maybe String) Api.Object.User
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


email : SelectionSet (Maybe String) Api.Object.User
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


phone : SelectionSet (Maybe String) Api.Object.User
phone =
    Object.selectionForField "(Maybe String)" "phone" [] (Decode.string |> Decode.nullable)


title : SelectionSet (Maybe String) Api.Object.User
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


address : SelectionSet (Maybe String) Api.Object.User
address =
    Object.selectionForField "(Maybe String)" "address" [] (Decode.string |> Decode.nullable)


lonlat : SelectionSet (Maybe Api.ScalarCodecs.Point) Api.Object.User
lonlat =
    Object.selectionForField "(Maybe ScalarCodecs.Point)" "lonlat" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecPoint |> .decoder |> Decode.nullable)


company : SelectionSet (Maybe String) Api.Object.User
company =
    Object.selectionForField "(Maybe String)" "company" [] (Decode.string |> Decode.nullable)


lastActivityAt : SelectionSet (Maybe String) Api.Object.User
lastActivityAt =
    Object.selectionForField "(Maybe String)" "lastActivityAt" [] (Decode.string |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.User
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.User
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


avatarCloudFile :
    SelectionSet decodesTo Api.Object.CloudFile
    -> SelectionSet (Maybe decodesTo) Api.Object.User
avatarCloudFile object_ =
    Object.selectionForCompositeField "avatarCloudFile" [] object_ (identity >> Decode.nullable)


projects :
    SelectionSet decodesTo Api.Object.Project
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.User
projects object_ =
    Object.selectionForCompositeField "projects" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


jurisdictions :
    SelectionSet decodesTo Api.Object.Jurisdiction
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.User
jurisdictions object_ =
    Object.selectionForCompositeField "jurisdictions" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


groups :
    SelectionSet decodesTo Api.Object.Group
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.User
groups object_ =
    Object.selectionForCompositeField "groups" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
