-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Version exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The ID of an object
-}
id : SelectionSet Api.ScalarCodecs.Id Api.Object.Version
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


isReady : SelectionSet (Maybe Bool) Api.Object.Version
isReady =
    Object.selectionForField "(Maybe Bool)" "isReady" [] (Decode.bool |> Decode.nullable)


tileSigningParams : SelectionSet (Maybe Api.ScalarCodecs.Json) Api.Object.Version
tileSigningParams =
    Object.selectionForField "(Maybe ScalarCodecs.Json)" "tileSigningParams" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecJson |> .decoder |> Decode.nullable)


processingStats : SelectionSet (Maybe Api.ScalarCodecs.Json) Api.Object.Version
processingStats =
    Object.selectionForField "(Maybe ScalarCodecs.Json)" "processingStats" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecJson |> .decoder |> Decode.nullable)


insertedAt : SelectionSet (Maybe String) Api.Object.Version
insertedAt =
    Object.selectionForField "(Maybe String)" "insertedAt" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet (Maybe String) Api.Object.Version
updatedAt =
    Object.selectionForField "(Maybe String)" "updatedAt" [] (Decode.string |> Decode.nullable)


document :
    SelectionSet decodesTo Api.Object.Document
    -> SelectionSet (Maybe decodesTo) Api.Object.Version
document object_ =
    Object.selectionForCompositeField "document" [] object_ (identity >> Decode.nullable)


cloudFile :
    SelectionSet decodesTo Api.Object.CloudFile
    -> SelectionSet (Maybe decodesTo) Api.Object.Version
cloudFile object_ =
    Object.selectionForCompositeField "cloudFile" [] object_ (identity >> Decode.nullable)


user :
    SelectionSet decodesTo Api.Object.User
    -> SelectionSet (Maybe decodesTo) Api.Object.Version
user object_ =
    Object.selectionForCompositeField "user" [] object_ (identity >> Decode.nullable)


pages :
    SelectionSet decodesTo Api.Object.Page
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Version
pages object_ =
    Object.selectionForCompositeField "pages" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


stampedDocuments :
    SelectionSet decodesTo Api.Object.StampedDocument
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Version
stampedDocuments object_ =
    Object.selectionForCompositeField "stampedDocuments" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
