-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.InspectionStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


type InspectionStatus
    = Passed
    | Failed


list : List InspectionStatus
list =
    [ Passed, Failed ]


decoder : Decoder InspectionStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PASSED" ->
                        Decode.succeed Passed

                    "FAILED" ->
                        Decode.succeed Failed

                    _ ->
                        Decode.fail ("Invalid InspectionStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : InspectionStatus -> String
toString enum =
    case enum of
        Passed ->
            "PASSED"

        Failed ->
            "FAILED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe InspectionStatus
fromString enumString =
    case enumString of
        "PASSED" ->
            Just Passed

        "FAILED" ->
            Just Failed

        _ ->
            Nothing
