-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.PunchListItemStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


type PunchListItemStatus
    = Fixed


list : List PunchListItemStatus
list =
    [ Fixed ]


decoder : Decoder PunchListItemStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "FIXED" ->
                        Decode.succeed Fixed

                    _ ->
                        Decode.fail ("Invalid PunchListItemStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : PunchListItemStatus -> String
toString enum =
    case enum of
        Fixed ->
            "FIXED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PunchListItemStatus
fromString enumString =
    case enumString of
        "FIXED" ->
            Just Fixed

        _ ->
            Nothing
