-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.SortDirection exposing (..)

import Json.Decode as Decode exposing (Decoder)


type SortDirection
    = Asc
    | AscNullsLast
    | AscNullsFirst
    | Desc
    | DescNullsLast
    | DescNullsFirst


list : List SortDirection
list =
    [ Asc, AscNullsLast, AscNullsFirst, Desc, DescNullsLast, DescNullsFirst ]


decoder : Decoder SortDirection
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ASC" ->
                        Decode.succeed Asc

                    "ASC_NULLS_LAST" ->
                        Decode.succeed AscNullsLast

                    "ASC_NULLS_FIRST" ->
                        Decode.succeed AscNullsFirst

                    "DESC" ->
                        Decode.succeed Desc

                    "DESC_NULLS_LAST" ->
                        Decode.succeed DescNullsLast

                    "DESC_NULLS_FIRST" ->
                        Decode.succeed DescNullsFirst

                    _ ->
                        Decode.fail ("Invalid SortDirection type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : SortDirection -> String
toString enum =
    case enum of
        Asc ->
            "ASC"

        AscNullsLast ->
            "ASC_NULLS_LAST"

        AscNullsFirst ->
            "ASC_NULLS_FIRST"

        Desc ->
            "DESC"

        DescNullsLast ->
            "DESC_NULLS_LAST"

        DescNullsFirst ->
            "DESC_NULLS_FIRST"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SortDirection
fromString enumString =
    case enumString of
        "ASC" ->
            Just Asc

        "ASC_NULLS_LAST" ->
            Just AscNullsLast

        "ASC_NULLS_FIRST" ->
            Just AscNullsFirst

        "DESC" ->
            Just Desc

        "DESC_NULLS_LAST" ->
            Just DescNullsLast

        "DESC_NULLS_FIRST" ->
            Just DescNullsFirst

        _ ->
            Nothing
